"""add mood to rollouts and precedent_traces

Revision ID: 16544e121c8c
Revises: 5f41601f3cef
Create Date: 2026-05-24 15:29:24.380717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16544e121c8c'
down_revision: Union[str, Sequence[str], None] = '5f41601f3cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('precedent_traces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mood', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_precedent_traces_mood'), ['mood'], unique=False)

    with op.batch_alter_table('rollouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mood', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_rollouts_mood'), ['mood'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rollouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rollouts_mood'))
        batch_op.drop_column('mood')

    with op.batch_alter_table('precedent_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_precedent_traces_mood'))
        batch_op.drop_column('mood')

    # ### end Alembic commands ###
