"""add query_text and query_hash to data_fetches (Q6b)

Revision ID: 4235c085f10e
Revises: c8a4f7f0ee0e
Create Date: 2026-06-02 12:11:07.556064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4235c085f10e'
down_revision: Union[str, Sequence[str], None] = 'c8a4f7f0ee0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_fetches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('query_hash', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_data_fetches_query_hash'), ['query_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_fetches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_fetches_query_hash'))
        batch_op.drop_column('query_hash')
        batch_op.drop_column('query_text')

    # ### end Alembic commands ###
