"""baseline schema

Revision ID: 8b87f48d49e6
Revises: 
Create Date: 2026-05-23 12:35:00.252543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b87f48d49e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sop_ref', sa.String(), nullable=False),
    sa.Column('sop_name', sa.String(), nullable=False),
    sa.Column('sop_snapshot', sa.JSON(), nullable=False),
    sa.Column('planner_mode', sa.String(), nullable=False),
    sa.Column('chat_mode', sa.String(), nullable=False),
    sa.Column('mcts_config', sa.JSON(), nullable=False),
    sa.Column('models', sa.JSON(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terminal_outcome', sa.String(), nullable=True),
    sa.Column('terminal_reward', sa.Float(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_terminal_outcome'), ['terminal_outcome'], unique=False)

    op.create_table('learning_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sop_ref', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('n_precedents', sa.Integer(), nullable=True),
    sa.Column('n_sessions', sa.Integer(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('proposals', sa.JSON(), nullable=False),
    sa.Column('accepted_proposal_ids', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_runs_sop_ref'), ['sop_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_runs_started_at'), ['started_at'], unique=False)

    op.create_table('sops',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_fetches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('cache_key', sa.String(), nullable=False),
    sa.Column('dependency_name', sa.String(), nullable=False),
    sa.Column('action_name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('issued_at_turn', sa.Integer(), nullable=False),
    sa.Column('predicted_turn', sa.Integer(), nullable=True),
    sa.Column('consumed_at_turn', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('fetch_duration_ms', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('payload_summary', sa.Text(), nullable=True),
    sa.Column('consumed', sa.Boolean(), nullable=True),
    sa.Column('wasted', sa.Boolean(), nullable=True),
    sa.Column('evicted', sa.Boolean(), nullable=True),
    sa.Column('speculative', sa.Boolean(), nullable=True),
    sa.Column('fetch_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_fetches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_fetches_cache_key'), ['cache_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_fetches_consumed'), ['consumed'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_fetches_dependency_name'), ['dependency_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_fetches_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_fetches_speculative'), ['speculative'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_fetches_wasted'), ['wasted'], unique=False)
        batch_op.create_index('ix_datafetch_exp_key', ['experiment_id', 'cache_key'], unique=False)

    op.create_table('pondering_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('after_turn_index', sa.Integer(), nullable=False),
    sa.Column('predicted_cohort', sa.String(), nullable=False),
    sa.Column('predicted_state', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('prior_prob', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('llm_calls_count', sa.Integer(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('consumed', sa.Boolean(), nullable=True),
    sa.Column('consumed_turn_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pondering_runs', schema=None) as batch_op:
        batch_op.create_index('ix_ponder_cache_key', ['experiment_id', 'after_turn_index', 'predicted_cohort', 'predicted_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_pondering_runs_after_turn_index'), ['after_turn_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_pondering_runs_consumed'), ['consumed'], unique=False)
        batch_op.create_index(batch_op.f('ix_pondering_runs_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pondering_runs_predicted_cohort'), ['predicted_cohort'], unique=False)
        batch_op.create_index(batch_op.f('ix_pondering_runs_predicted_state'), ['predicted_state'], unique=False)

    op.create_table('turns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('user_sim_ms', sa.Integer(), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('assistant_message', sa.Text(), nullable=True),
    sa.Column('chosen_action', sa.String(), nullable=True),
    sa.Column('predicted_user_state', sa.String(), nullable=True),
    sa.Column('state_rationale', sa.Text(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('mcts_iterations', sa.Integer(), nullable=True),
    sa.Column('rollouts', sa.Integer(), nullable=True),
    sa.Column('trace', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.create_index('ix_turns_exp_turn', ['experiment_id', 'turn_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_turns_experiment_id'), ['experiment_id'], unique=False)

    op.create_table('llm_calls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=True),
    sa.Column('turn_id', sa.String(), nullable=True),
    sa.Column('call_site', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('user_prompt', sa.Text(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('response_json', sa.JSON(), nullable=True),
    sa.Column('is_json_mode', sa.Boolean(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_calls_call_site'), ['call_site'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_calls_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_calls_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_calls_turn_id'), ['turn_id'], unique=False)

    op.create_table('mcts_candidates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('turn_id', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('q_value', sa.Float(), nullable=True),
    sa.Column('visits', sa.Integer(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('was_chosen', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcts_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcts_candidates_turn_id'), ['turn_id'], unique=False)

    op.create_table('precedent_retrievals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('turn_id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('sop_ref', sa.String(), nullable=False),
    sa.Column('cohort', sa.String(), nullable=False),
    sa.Column('query_situation_text', sa.Text(), nullable=True),
    sa.Column('top_k_requested', sa.Integer(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('used_expand', sa.Boolean(), nullable=True),
    sa.Column('used_score', sa.Boolean(), nullable=True),
    sa.Column('used_response', sa.Boolean(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('precedent_retrievals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_precedent_retrievals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_precedent_retrievals_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_precedent_retrievals_turn_id'), ['turn_id'], unique=True)

    op.create_table('precedent_traces',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('turn_id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('sop_ref', sa.String(), nullable=False),
    sa.Column('cohort', sa.String(), nullable=False),
    sa.Column('situation_text', sa.Text(), nullable=False),
    sa.Column('situation_embedding', sa.LargeBinary(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('immediate_state', sa.String(), nullable=True),
    sa.Column('immediate_reward', sa.Float(), nullable=True),
    sa.Column('terminal_outcome', sa.String(), nullable=True),
    sa.Column('terminal_reward', sa.Float(), nullable=True),
    sa.Column('turn_distance_to_terminal', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('precedent_traces', schema=None) as batch_op:
        batch_op.create_index('ix_prec_action_outcome', ['action', 'terminal_outcome'], unique=False)
        batch_op.create_index('ix_prec_cohort_sop', ['sop_ref', 'cohort'], unique=False)
        batch_op.create_index(batch_op.f('ix_precedent_traces_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_precedent_traces_cohort'), ['cohort'], unique=False)
        batch_op.create_index(batch_op.f('ix_precedent_traces_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_precedent_traces_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_precedent_traces_immediate_state'), ['immediate_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_precedent_traces_sop_ref'), ['sop_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_precedent_traces_terminal_outcome'), ['terminal_outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_precedent_traces_turn_id'), ['turn_id'], unique=True)

    op.create_table('rollouts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('turn_id', sa.String(), nullable=False),
    sa.Column('rollout_index', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('first_action', sa.String(), nullable=True),
    sa.Column('planned_actions', sa.JSON(), nullable=False),
    sa.Column('final_state', sa.String(), nullable=True),
    sa.Column('depth_completed', sa.Integer(), nullable=True),
    sa.Column('hit_failure', sa.Boolean(), nullable=True),
    sa.Column('hit_success', sa.Boolean(), nullable=True),
    sa.Column('rationality', sa.Float(), nullable=True),
    sa.Column('progress_bonus', sa.Float(), nullable=True),
    sa.Column('reward', sa.Float(), nullable=True),
    sa.Column('rollout_mode', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rollouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rollouts_rollout_mode'), ['rollout_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_rollouts_turn_id'), ['turn_id'], unique=False)

    op.create_table('router_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('turn_id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('sop_ref', sa.String(), nullable=False),
    sa.Column('cohort', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('tier_used', sa.String(), nullable=False),
    sa.Column('entropy', sa.Float(), nullable=True),
    sa.Column('supporting_traces', sa.Integer(), nullable=True),
    sa.Column('dominant_action', sa.String(), nullable=True),
    sa.Column('dominant_agreement', sa.Float(), nullable=True),
    sa.Column('action_distribution', sa.JSON(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('router_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_router_decisions_cohort'), ['cohort'], unique=False)
        batch_op.create_index(batch_op.f('ix_router_decisions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_router_decisions_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_router_decisions_sop_ref'), ['sop_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_router_decisions_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_router_decisions_tier_used'), ['tier_used'], unique=False)
        batch_op.create_index(batch_op.f('ix_router_decisions_turn_id'), ['turn_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('router_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_router_decisions_turn_id'))
        batch_op.drop_index(batch_op.f('ix_router_decisions_tier_used'))
        batch_op.drop_index(batch_op.f('ix_router_decisions_state'))
        batch_op.drop_index(batch_op.f('ix_router_decisions_sop_ref'))
        batch_op.drop_index(batch_op.f('ix_router_decisions_experiment_id'))
        batch_op.drop_index(batch_op.f('ix_router_decisions_created_at'))
        batch_op.drop_index(batch_op.f('ix_router_decisions_cohort'))

    op.drop_table('router_decisions')
    with op.batch_alter_table('rollouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rollouts_turn_id'))
        batch_op.drop_index(batch_op.f('ix_rollouts_rollout_mode'))

    op.drop_table('rollouts')
    with op.batch_alter_table('precedent_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_precedent_traces_turn_id'))
        batch_op.drop_index(batch_op.f('ix_precedent_traces_terminal_outcome'))
        batch_op.drop_index(batch_op.f('ix_precedent_traces_sop_ref'))
        batch_op.drop_index(batch_op.f('ix_precedent_traces_immediate_state'))
        batch_op.drop_index(batch_op.f('ix_precedent_traces_experiment_id'))
        batch_op.drop_index(batch_op.f('ix_precedent_traces_created_at'))
        batch_op.drop_index(batch_op.f('ix_precedent_traces_cohort'))
        batch_op.drop_index(batch_op.f('ix_precedent_traces_action'))
        batch_op.drop_index('ix_prec_cohort_sop')
        batch_op.drop_index('ix_prec_action_outcome')

    op.drop_table('precedent_traces')
    with op.batch_alter_table('precedent_retrievals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_precedent_retrievals_turn_id'))
        batch_op.drop_index(batch_op.f('ix_precedent_retrievals_experiment_id'))
        batch_op.drop_index(batch_op.f('ix_precedent_retrievals_created_at'))

    op.drop_table('precedent_retrievals')
    with op.batch_alter_table('mcts_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcts_candidates_turn_id'))

    op.drop_table('mcts_candidates')
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_calls_turn_id'))
        batch_op.drop_index(batch_op.f('ix_llm_calls_started_at'))
        batch_op.drop_index(batch_op.f('ix_llm_calls_experiment_id'))
        batch_op.drop_index(batch_op.f('ix_llm_calls_call_site'))

    op.drop_table('llm_calls')
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turns_experiment_id'))
        batch_op.drop_index('ix_turns_exp_turn')

    op.drop_table('turns')
    with op.batch_alter_table('pondering_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pondering_runs_predicted_state'))
        batch_op.drop_index(batch_op.f('ix_pondering_runs_predicted_cohort'))
        batch_op.drop_index(batch_op.f('ix_pondering_runs_experiment_id'))
        batch_op.drop_index(batch_op.f('ix_pondering_runs_consumed'))
        batch_op.drop_index(batch_op.f('ix_pondering_runs_after_turn_index'))
        batch_op.drop_index('ix_ponder_cache_key')

    op.drop_table('pondering_runs')
    with op.batch_alter_table('data_fetches', schema=None) as batch_op:
        batch_op.drop_index('ix_datafetch_exp_key')
        batch_op.drop_index(batch_op.f('ix_data_fetches_wasted'))
        batch_op.drop_index(batch_op.f('ix_data_fetches_speculative'))
        batch_op.drop_index(batch_op.f('ix_data_fetches_experiment_id'))
        batch_op.drop_index(batch_op.f('ix_data_fetches_dependency_name'))
        batch_op.drop_index(batch_op.f('ix_data_fetches_consumed'))
        batch_op.drop_index(batch_op.f('ix_data_fetches_cache_key'))

    op.drop_table('data_fetches')
    op.drop_table('sops')
    with op.batch_alter_table('learning_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_learning_runs_sop_ref'))

    op.drop_table('learning_runs')
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiments_terminal_outcome'))
        batch_op.drop_index(batch_op.f('ix_experiments_created_at'))

    op.drop_table('experiments')
    # ### end Alembic commands ###
