"""add pool_picks table for pool-rerank architecture

Revision ID: 98d272f4cc6d
Revises: 4235c085f10e
Create Date: 2026-06-03 09:39:56.286292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98d272f4cc6d'
down_revision: Union[str, Sequence[str], None] = '4235c085f10e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pool_picks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('picked_fetch_ids', sa.JSON(), nullable=False),
    sa.Column('pool_size_at_pick', sa.Integer(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('pick_duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pool_picks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pool_picks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pool_picks_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pool_picks_turn_index'), ['turn_index'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pool_picks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pool_picks_turn_index'))
        batch_op.drop_index(batch_op.f('ix_pool_picks_experiment_id'))
        batch_op.drop_index(batch_op.f('ix_pool_picks_created_at'))

    op.drop_table('pool_picks')
    # ### end Alembic commands ###
