"""add planned_user_texts to rollouts (Q6b)

Revision ID: c8a4f7f0ee0e
Revises: edf42eca87b0
Create Date: 2026-06-02 11:25:04.024815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a4f7f0ee0e'
down_revision: Union[str, Sequence[str], None] = 'edf42eca87b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema. server_default supplies '[]' for any pre-existing rollouts so the
    NOT NULL constraint can be satisfied. New inserts use the Python-side default.
    Same pattern as planned_states migration (5f41601f3cef)."""
    with op.batch_alter_table('rollouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'planned_user_texts', sa.JSON(), nullable=False, server_default=sa.text("'[]'"),
        ))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rollouts', schema=None) as batch_op:
        batch_op.drop_column('planned_user_texts')

    # ### end Alembic commands ###
