"""add mood column to turns

Revision ID: edf42eca87b0
Revises: 16544e121c8c
Create Date: 2026-05-29 09:51:21.159609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf42eca87b0'
down_revision: Union[str, Sequence[str], None] = '16544e121c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mood', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_turns_mood'), ['mood'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turns_mood'))
        batch_op.drop_column('mood')

    # ### end Alembic commands ###
