"""add rollout_action_policy to rollouts

Revision ID: f67b4d39826c
Revises: 8b87f48d49e6
Create Date: 2026-05-23 13:33:50.191212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f67b4d39826c'
down_revision: Union[str, Sequence[str], None] = '8b87f48d49e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rollouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rollout_action_policy', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_rollouts_rollout_action_policy'), ['rollout_action_policy'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rollouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rollouts_rollout_action_policy'))
        batch_op.drop_column('rollout_action_policy')

    # ### end Alembic commands ###
